version: '3.7'

services:
  database:
    image: postgres:latest
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=demodb"
    ports:
      - "45432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080